appname       : "pbdata"
apptitle      : "Paleobiology Data Services"
appdesc	      : "fossils of the world"
appauthor     : "Michael McClennen"
appauthoremail: "mmcclenn@geology.wisc.edu"
appversion    : "0.1"
applicense    : "CC0 waiver"
hostname      : "testpaleodb.geology.wisc.edu"

layout: "main"
charset: "UTF-8"
template: "tiny"

plugins:
    Database:
      driver: 'mysql'
      database: 'pbdb'
      host: 'localhost:mysql_socket=/opt/local/var/run/mariadb/mysqld.sock'
      username: 'john'
      password: 'zeppelin'
      dbi_params:
        AutoCommit: 1
