#
# This file was generated by Claude (Anthropic) in collaboration with
# a user, through an iterative conversation refining its geological
# accuracy, scope, and structure. See the notes below for the full
# methodology and every simplification/judgment call made along the
# way.
#
# $neighbor{$a}{$b} is true iff country $a and country $b
# (ISO 3166-1 alpha-2 codes) share a LAND border, OR share a MARITIME
# border and sit on the same major tectonic plate.
#
# This is a GEOLOGICAL adjacency structure, not a political one: e.g.
# France and the United Kingdom are linked (English Channel, both
# Eurasian Plate), but Iran and Saudi Arabia are NOT (Persian Gulf,
# but opposite sides of an active plate boundary), even though both
# pairs are "neighbouring countries" in the everyday political sense.
#
# Sources:
#  - Land/maritime border list: Wikipedia, "List of countries and
#    territories by land and maritime borders"
#    https://en.wikipedia.org/wiki/List_of_countries_and_territories_by_land_and_maritime_borders
#  - Tectonic plate membership: standard major-plate classification
#    (Wikipedia's plate articles, e.g. "African plate", "Eurasian
#    plate", "North American plate", etc.), supplemented with a small
#    number of well-established minor/microplates where using only
#    the ~7-8 "major" plates would misrepresent well-known boundaries
#    (Arabian, Caribbean, Sunda, Philippine Sea, Anatolian, Aegean
#    Sea, Somali, Burma).
#
# ----------------------------------------------------------------
# IMPORTANT METHODOLOGICAL NOTES / SIMPLIFICATIONS
# ----------------------------------------------------------------
#  1. EVERY ISO 3166-1 ALPHA-2 CODE gets a hash entry: all fully
#     sovereign states, PLUS every non-sovereign territory/dependency
#     that has been assigned its own separate code (Greenland, Hong
#     Kong, Puerto Rico, French Guiana, and so on - see note 3 for the
#     complete list and their sourcing). Each such territory is judged
#     on ITS OWN geology and ITS OWN real borders (per the source
#     page, or reasoned from general geography where the source page
#     doesn't cover it - flagged where that happens), rather than
#     being merged into its parent sovereign state's code. Disputed
#     entities with NO official ISO code (Kosovo, Somaliland,
#     Abkhazia, South Ossetia, Transnistria, Northern Cyprus, Artsakh)
#     are still omitted entirely, since there is no code to hold them.
#     Western Sahara (EH) and Palestine (PS) are included and treated
#     as sovereign, per the source page's own convention.
#     Antarctica (AQ) and the various national Antarctic TERRITORIAL
#     CLAIMS (Argentine Antarctica, Chilean Antarctic Territory,
#     British Antarctic Territory, Australian Antarctic Territory,
#     Queen Maud Land, Ross Dependency, Adelie Land) are excluded,
#     matching the source page's own explicit convention of leaving
#     overlapping, largely unrecognised Antarctic claims out of its
#     border listings entirely.
#
#  2. EVERY COUNTRY IS ASSIGNED ONE "PRIMARY" PLATE for its %plate
#     entry and for most matching purposes. Real geology is messier:
#     many countries straddle plate boundaries. Per your instruction,
#     where a country/territory genuinely straddles two plates, it
#     CAN still match a neighbour on whichever plate is actually
#     relevant to that specific shared border, even though its
#     %plate entry only names one "primary" plate. These are called
#     out explicitly below and in the pair lists further down (search
#     for "SPLIT-PLATE EXCEPTION").
#       - Russia, China, Mongolia, the Koreas: %plate says wholly
#         Eurasian, ignoring the Amurian/Okhotsk microplates some
#         models assign to Far East Russia, NE China and the Korean
#         peninsula. SPLIT-PLATE EXCEPTION: Russia's Chukotka
#         Peninsula (the Bering Strait region) is, in most models,
#         actually on the North American Plate - so RU-US is
#         included as a same-plate match there, despite Russia's
#         %plate entry saying Eurasian.
#       - Iran, Afghanistan: treated as wholly Eurasian Plate,
#         ignoring the small Central Iran/Lut microplates some models
#         use.
#       - Pakistan, India, Nepal, Bhutan, Bangladesh, Sri Lanka,
#         Maldives: treated as Indian Plate.
#       - New Zealand: %plate says Australian Plate (matching
#         Australia, Timor-Leste, Papua New Guinea, Norfolk Island,
#         New Caledonia), but the eastern South Island is, in most
#         models, on the Pacific Plate side of the Alpine Fault.
#         SPLIT-PLATE EXCEPTION: NZ-FJ, NZ-TO, NZ-WS, and NZ-KI are
#         included as Pacific-Plate matches on that basis.
#       - Iceland: %plate says Eurasian (matching the Faroe Islands,
#         Svalbard/Jan Mayen), but Iceland sits astride the
#         Mid-Atlantic Ridge and its western half is on the North
#         American Plate. SPLIT-PLATE EXCEPTION: IS-GL (Greenland) is
#         included on that basis.
#       - Indonesia: %plate says Sunda Plate (matching Malaysia,
#         Brunei, Thailand, etc via Sumatra/Java/Borneo), but
#         Indonesian Papua (the western half of the island of New
#         Guinea) and the Aru Islands sit on the Australian Plate's
#         Sahul Shelf, the same continental margin as Australia and
#         Papua New Guinea. SPLIT-PLATE EXCEPTION: ID-PG and ID-AU
#         are included on that basis. (Timor is deliberately NOT
#         included here despite similar proximity - the Indonesia/
#         Timor-Leste boundary runs through an active
#         subduction/collision zone, not a shared passive margin, so
#         it doesn't meet the same "plausibly shares strata" bar.)
#       - Japan: physically sits across parts of four plates
#         (Okhotsk/North American, Amurian/Eurasian, Philippine Sea,
#         and the subducting Pacific Plate), so no single %plate
#         entry is given for it. SPLIT-PLATE EXCEPTIONS: JP-CN,
#         JP-KP, and JP-KR are included, since most of Japan (and
#         all of mainland China/Korea, per THEIR simplified %plate
#         entries above) sits on the Amurian/Eurasian side; JP-PH is
#         included, since Japan's Ryukyu/Izu-Bonin chain sits on the
#         Philippine Sea Plate, matching the Philippines. JP-RU and
#         JP-TW remain EXCLUDED: Japan's Hokkaido/Kuril portion
#         (Okhotsk/North American) doesn't match Russia's simplified
#         Eurasian %plate entry, and Japan's Ryukyu portion
#         (Philippine Sea) doesn't match Taiwan's simplified Eurasian
#         %plate entry - both of those really are convergent
#         subduction boundaries between genuinely different plates.
#       - Myanmar is treated as its own Burma microplate, distinct
#         from all its neighbours on every side - it has no
#         plate-based maritime matches, split-plate or otherwise.
#
#  3. TERRITORIES ARE TREATED AS FIRST-CLASS ENTITIES IN THEIR OWN
#     RIGHT, not folded into their parent sovereign state, wherever
#     they carry their own separate ISO 3166-1 alpha-2 code. Each was
#     assigned its own plate and its own real borders (from the
#     source page), independent of its parent state's plate:
#       - France's overseas entities: French Guiana (GF, South
#         American Plate: land borders with Brazil and Suriname),
#         Reunion (RE, Somali Plate: Mauritius, Seychelles,
#         Madagascar), Mayotte (YT, Somali Plate: Comoros),
#         Martinique (MQ) and Guadeloupe (GP, both Caribbean Plate),
#         Saint Martin (MF, Caribbean Plate: land border with Sint
#         Maarten, since the two share one island), Saint Barthelemy
#         (BL, Caribbean Plate), New Caledonia (NC, Australian
#         Plate - part of the submerged Zealandia continent, so it
#         does NOT match Fiji/Vanuatu/Solomon Islands, which sit on
#         the Pacific Plate on the other side of a real subduction
#         boundary), French Polynesia (PF, Pacific Plate: Kiribati),
#         Wallis and Futuna (WF, Pacific Plate: Fiji, Samoa, Tonga,
#         Tuvalu), Saint Pierre and Miquelon (PM, North American
#         Plate: Canada). Note that mainland France (FR) itself keeps
#         only its own genuine borders: Andorra, Spain, Italy,
#         Switzerland, Germany, Belgium, Luxembourg, Monaco (land),
#         and the UK (maritime, English Channel).
#       - The source page doesn't distinguish Martinique from
#         Guadeloupe by name for their Lesser Antilles maritime
#         borders (both just appear as generic "France"), so which of
#         the two borders Antigua & Barbuda, Barbados, Dominica,
#         Saint Lucia, and Montserrat was assigned by straightforward
#         geography (Guadeloupe is the more northerly island,
#         Martinique the more southerly) - flagged here as the one
#         genuinely approximate part of this section.
#       - UK's overseas territories: Falkland Islands (FK, South
#         American Plate: Argentina), Cayman Islands (KY, Caribbean
#         Plate: Honduras, Jamaica - NOT Cuba, which is North
#         American Plate), Turks and Caicos (TC, North American
#         Plate, Bahamas platform: Bahamas - NOT Dominican
#         Republic/Haiti, which are Caribbean Plate), Anguilla (AI)
#         and Montserrat (MS, both Caribbean Plate), British Virgin
#         Islands (VG, Caribbean Plate), British Indian Ocean
#         Territory (IO, Indian Plate: Maldives), Gibraltar (GI,
#         Eurasian Plate: land border with Spain), and Bermuda (BM,
#         North American Plate, but has NO borders of any kind per
#         the source page). Mainland UK (GB) keeps its own genuine
#         borders: Ireland (land), plus Belgium, Denmark, France,
#         Germany, Netherlands, Norway (all maritime, all Eurasian
#         Plate). Mainland UK (GB) keeps its own genuine borders:
#         Ireland (land), plus Belgium, Denmark, France, Germany,
#         Netherlands, Norway (all maritime, all Eurasian Plate). UK's
#         Akrotiri and Dhekelia Sovereign Base Areas (no separate ISO
#         code) share a land border with Cyprus, but this is EXCLUDED
#         (see note 5) - Akrotiri/Dhekelia is a small military base
#         exclave on Cyprus itself, not plausibly sharing strata with
#         Great Britain.
#       - Netherlands' Caribbean countries: Aruba (AW) and Curacao
#         (CW), both South American Plate (the "ABC islands" sit on
#         the continental shelf, unlike the volcanic Lesser
#         Antilles), and Sint Maarten (SX), Caribbean Plate. Mainland
#         Netherlands (NL) keeps only its genuine maritime match with
#         the UK (North Sea, both Eurasian Plate).
#       - US territories: Puerto Rico (PR), US Virgin Islands (VI),
#         and Guam/Northern Mariana Islands (GU, MP - both Philippine
#         Sea Plate, matching each other but not nearby Pacific-Plate
#         Micronesia/FSM), and American Samoa (AS, Pacific Plate:
#         Samoa, Tonga). Mainland US (US) keeps only its genuine
#         mainland/near-mainland matches: Canada, Mexico, Cuba, the
#         Bahamas.
#       - Denmark's Faroe Islands (FO, Eurasian Plate: Iceland,
#         Norway, UK) and Greenland (GL, North American Plate: land
#         border with Canada - see also the Iceland split-plate
#         exception in note 2). Mainland Denmark (DK) keeps its own
#         genuine matches only.
#       - Norway's Svalbard and Jan Mayen (both under the single ISO
#         code SJ, Eurasian Plate: Norway, Russia, Iceland) and Bouvet
#         Island (BV, no borders per the source page).
#       - Finland's Aland Islands (AX, Eurasian Plate: Sweden, Norway,
#         Finland).
#       - Australia's Christmas Island (CX, Australian Plate, but no
#         same-plate matches - its only listed neighbour, Indonesia,
#         is Sunda Plate, genuinely across the Sunda Trench
#         subduction zone), Cocos Islands (CC, Australian Plate, no
#         borders per the source page), Norfolk Island (NF,
#         Australian Plate: New Zealand, New Caledonia - part of the
#         same submerged Zealandia block), and Heard Island and
#         McDonald Islands (HM, treated as Antarctic Plate - see the
#         French Southern Territories entry just below).
#       - New Zealand's Cook Islands (CK), Niue (NU), and Tokelau (TK)
#         - all three treated as Pacific Plate, matching Kiribati,
#         American Samoa, French Polynesia, Samoa, Tonga, Wallis and
#         Futuna, and each other.
#       - UK's Crown Dependencies, Guernsey (GG) and Jersey (JE, both
#         Eurasian Plate: mainland France, mainland UK, and each
#         other), and Isle of Man (IM, Eurasian Plate: mainland UK).
#         Also Pitcairn Islands (PN, Pacific Plate: French Polynesia),
#         and Saint Helena, Ascension and Tristan da Cunha and South
#         Georgia and the South Sandwich Islands (SH, GS - both have
#         no borders per the source page).
#       - China's Hong Kong (HK) and Macau (MO), both treated as
#         Eurasian Plate: each has a genuine land border with mainland
#         China.
#       - The Netherlands' Bonaire, Sint Eustatius and Saba (BQ) - a
#         SINGLE ISO code covering geographically separate islands on
#         DIFFERENT plates (Bonaire, next to Curacao/Aruba, is South
#         American Plate; Saba and Sint Eustatius, next to Saint Kitts,
#         are Caribbean Plate). Per the split-plate policy in note 2,
#         BQ is matched on whichever side is relevant: BQ-VE, BQ-AW,
#         BQ-CW (Bonaire/South American side) and BQ-KN, BQ-SX, BQ-BL
#         (Saba & Sint Eustatius/Caribbean side). Unlike the other
#         entries in this note, the source page has no row at all for
#         BQ, so these are reasoned from general geography rather than
#         sourced from the page - flagged as the least-certain entries
#         in this file.
#       - France's French Southern and Antarctic Lands (TF) - another
#         single code spanning genuinely different regions: the
#         Indian Ocean "Scattered Islands" near Madagascar (grouped
#         here with the Somali Plate, matching Comoros, Madagascar,
#         Mauritius, Seychelles) and the sub-Antarctic Kerguelen/Crozet
#         group (grouped with Heard Island, both loosely "Antarctic
#         Plate"). Per the split-plate policy, TF-MZ (Mozambique) is
#         ALSO included, since the westernmost Scattered Islands
#         (Bassas da India, Europa, Juan de Nova) sit closer to the
#         African Plate side of the Mozambique Channel. This is the
#         most geologically approximate entry in the whole file: the
#         source page doesn't say which specific island creates which
#         specific border, and several of these islands' exact plate
#         affiliation is itself unsettled science.
#       - The US's United States Minor Outlying Islands (UM) - a
#         single code bundling nine scattered, mostly-uninhabited
#         US-administered islands, spanning BOTH the Pacific Plate
#         (Baker, Howland, Jarvis, Kingman Reef, Palmyra Atoll, Wake
#         Island) and the Caribbean Plate (Navassa Island, disputed
#         with Haiti). Per the split-plate policy: UM-KI and UM-MH
#         (Pacific side, sourced from the individual islands' own rows
#         on the source page) and UM-HT, UM-JM (Caribbean side, via
#         Navassa, also sourced). UM-CU is excluded, since Navassa's
#         Caribbean Plate doesn't match Cuba's North American Plate.
#
#  4. Trinidad and Tobago and the Dutch ABC islands (Aruba, Curacao,
#     Bonaire) are treated as South American Plate (Leeward Antilles
#     / continental shelf), NOT Caribbean Plate, distinguishing them
#     from the volcanic Lesser Antilles arc (Caribbean Plate:
#     Antigua & Barbuda, Dominica, Grenada, St Kitts & Nevis, St
#     Lucia, St Vincent & the Grenadines, Barbados) and from Central
#     America south of the Motagua Fault (also Caribbean Plate:
#     Honduras, El Salvador, Nicaragua, Costa Rica, Panama, plus
#     Jamaica, Haiti, Dominican Republic, Cuba... note Cuba and the
#     Bahamas are instead treated as North American Plate, per the
#     Bahamas carbonate platform).
#
#  5. SMALL FOREIGN EXCLAVES WITHOUT THEIR OWN ISO CODE ARE EXCLUDED
#     ENTIRELY, even where a real, named land border exists, when the
#     exclave sits on entirely different geological terrain from its
#     parent state and could not plausibly share strata with it. This
#     is a step beyond note 3 (which only excludes territories that
#     have their OWN code): here, the exclave has no separate code,
#     but attributing its border to the parent is still geologically
#     implausible.
#       - UK / Cyprus: the Akrotiri and Dhekelia Sovereign Base Areas
#         are a small military-base exclave physically located ON the
#         island of Cyprus. They have no separate ISO code, but they
#         obviously do not share geological strata with Great
#         Britain, so this border is EXCLUDED (no GB-CY entry).
#       - Spain / Morocco: the border(s) via Ceuta and Melilla (which
#         also have no separate ISO code - they're Spanish autonomous
#         cities, not separately coded territories) sit on the North
#         African mainland immediately next to Morocco, in the same
#         Rif/Betic-Rif orogenic belt as Morocco itself - not
#         plausibly the same strata as mainland Iberia. This border is
#         likewise EXCLUDED (no ES-MA entry), even though Spain-Morocco
#         is otherwise a genuine, well-known land border.
#
#  6. This is inherently a matter of ongoing scientific classification
#     for microplates and boundary regions - treat this as a
#     reasonable, documented approximation, not a definitive geological
#     authority.
#
# %plate is provided below for transparency, so you can see/audit the
# assignment used to generate the maritime portion of %neighbor.

use strict;
use warnings;

package GeologicalNeighbors;

use base 'Exporter';
our @EXPORT_OK = qw(%neighbor);

our %neighbor;
our %plate;

my @plate_lines = split /\n/, <<'END_PLATES2';
Eurasian: PT ES FR MC AD IT SM VA CH LI AT DE BE NL LU GB IE DK NO SE FI IS PL CZ SK HU RO BG MD UA BY LT LV EE RU MN CN KP KR TW AF IR KZ UZ TM KG TJ AL
African: MA DZ TN LY EG EH MR ML SN GM GW GN SL LR CI BF GH TG BJ NE TD CF CM GQ GA CG CD AO ZM MW MZ ZW NA BW ZA LS SZ CV ST NG BI RW UG SS SD IL PS LB MT ET DJ ER
Somali: SO KE TZ MG KM SC MU
Arabian: SA YE OM AE QA BH KW IQ SY JO
Indian: IN PK NP BT BD LK MV
Burma: MM
Sunda: ID MY BN TH KH LA VN SG
PhilippineSea: PH PW
Australian: AU NZ PG TL
Pacific: FJ TO WS KI TV NR MH FM SB VU
NorthAmerican: US CA MX CU BS GT BZ
Caribbean: HN SV NI CR PA JM HT DO AG DM GD KN LC VC BB
SouthAmerican: CO VE GY SR BR EC PE BO PY CL AR UY TT
Anatolian: TR CY
AegeanSea: GR
Eurasian: AX FO GG HK IM JE MO SJ
NorthAmerican: GL
Australian: CC CX NF
Pacific: CK NU PN TK
Antarctic: BV HM
African: SH
Scotia: GS
Somali: TF
Mixed: BQ UM JP
Eurasian: GI
SouthAmerican: GF FK AW CW
Somali: RE YT
Caribbean: MQ GP MF BL KY AI MS VG SX PR VI
Australian: NC
Pacific: PF WF AS
NorthAmerican: PM TC BM
Indian: IO
PhilippineSea: GU MP
END_PLATES2

for my $line (@plate_lines) {
    my ($plate_name, $codes) = split /:\s*/, $line, 2;
    next unless defined $codes;
    for my $code (split ' ', $codes) {
        $plate{$code} = $plate_name;
    }
}

# --- Land borders --------------------------------------------------
# Each line is one undirected pair "XX YY" of ISO 3166-1 alpha-2 codes
# sharing a LAND border.
my @land_pairs = split /\n/, <<'END_PAIRS';
AF CN
AF IR
AF PK
AF TJ
AF TM
AF UZ
AD FR
AD ES
AO CD
AO CG
AO NA
AO ZM
AR BO
AR BR
AR CL
AR PY
AR UY
AM AZ
AM GE
AM IR
AM TR
AT CZ
AT DE
AT HU
AT IT
AT LI
AT SK
AT SI
AT CH
AZ GE
AZ IR
AZ RU
AZ TR
BD IN
BD MM
BY LV
BY LT
BY PL
BY RU
BY UA
BE FR
BE DE
BE LU
BE NL
BZ GT
BZ MX
BJ BF
BJ NE
BJ NG
BJ TG
BT CN
BT IN
BO BR
BO CL
BO PY
BO PE
BA HR
BA ME
BA RS
BW NA
BW ZA
BW ZM
BW ZW
BR CO
BR GY
BR PY
BR PE
BR UY
BR VE
BN MY
BG GR
BG MK
BG RO
BG RS
BG TR
BF CI
BF GH
BF ML
BF NE
BF TG
BI CD
BI RW
BI TZ
KH LA
KH TH
KH VN
CM CF
CM TD
CM CG
CM GQ
CM GA
CM NG
CA US
CF TD
CF CD
CF CG
CF SS
CF SD
TD LY
TD NE
TD NG
TD SD
CL PE
CN IN
CN KZ
CN KP
CN KG
CN LA
CN MN
CN NP
CN PK
CN RU
CN TJ
CN VN
CO EC
CO PA
CO PE
CO VE
CD CG
CD RW
CD SS
CD TZ
CD UG
CD ZM
CR NI
CR PA
CI GH
CI GN
CI ML
HR HU
HR ME
HR RS
HR SI
CZ DE
CZ PL
CZ SK
DK DE
DJ ER
DJ ET
DO HT
TL ID
EC PE
EG IL
EG LY
EG SD
EG PS
SV GT
SV HN
GQ GA
ER SD
ER ET
EE LV
EE RU
SZ MZ
SZ ZA
ET KE
ET SO
ET SS
ET SD
FR DE
FR IT
FR LU
FR MC
FR ES
FR CH
GM SN
GE RU
GE TR
DE LU
DE NL
DE PL
DE CH
GH TG
GR MK
GR TR
GT HN
GT MX
GN GW
GN LR
GN ML
GN SN
GN SL
GW SN
GY SR
GY VE
HN NI
HU RO
HU RS
HU SK
HU UA
IN NP
IN PK
ID MY
ID PG
IR IQ
IR PK
IR TR
IR TM
IQ JO
IQ KW
IQ SA
IQ SY
IQ TR
IE GB
IL JO
IL LB
IL SY
IL PS
IT SM
IT SI
IT CH
IT VA
JO SA
JO SY
JO PS
KZ KG
KZ RU
KZ TM
KZ UZ
KE SO
KE SS
KE TZ
KE UG
KW SA
KG TJ
KG UZ
LA TH
LA VN
LV LT
LV RU
LB SY
LR SL
LY DZ
LY TN
LT PL
LT RU
MW MZ
MW TZ
MW ZM
MY TH
ML DZ
ML MR
ML NE
ML SN
MR DZ
MR SN
MR EH
MX US
MD RO
MD UA
MN RU
ME RS
MA EH
MA DZ
MZ TZ
MZ ZM
MZ ZW
MM TH
NA ZA
NA ZM
NE DZ
NE LY
NE NG
KP KR
KP RU
MK RS
NO FI
NO RU
NO SE
OM SA
OM AE
OM YE
PL RU
PL SK
PL UA
QA SA
RO RS
RO UA
RU UA
RW TZ
RW UG
SA YE
SK UA
ZA ZW
SS SD
SS UG
ES PT
SY TR
TJ UZ
TZ UG
TZ ZM
TM UZ
AE SA
ZM ZW
DZ TN
AL GR
AL ME
AL MK
GF BR
GF SR
MF SX
GI ES
GL CA
HK CN
MO CN
END_PAIRS

# --- Maritime borders between countries on the SAME tectonic plate --
# Derived by taking every maritime-only (M) relationship on the source
# page between two ISO-coded sovereign states, then keeping only the
# ones where both sides (per the notes above, using the actual
# bordering territory's geology for multi-plate states) are on the
# same plate.
my @maritime_same_plate_pairs = split /\n/, <<'END_MPAIRS';
AL IT
AU TL
AU NZ
AU PG
AZ KZ
AZ TM
BS CU
BS US
BH QA
BH SA
BB LC
BB VC
BE GB
BN VN
BG RU
BG UA
CV GM
CV MR
CV SN
CN KR
CN TW
KM MG
KM SC
KM TZ
HR IT
CU MX
CU US
CY TR
DK NO
DK PL
DK SE
DK GB
SV NI
GQ NG
GQ ST
EE FI
EE SE
FJ SB
FJ TO
FJ TV
FJ VU
FR GB
GA ST
GD VC
GY TT
HT JM
HN JM
IN MV
IN LK
ID SG
ID TH
ID VN
IT ME
IT ES
JM NI
KI MH
KI NR
KI TV
KR RU
LV SE
LY MT
LT SE
MG MU
MG SC
MY SG
MY VN
MV LK
MH FM
MH NR
MU SC
NG ST
NL GB
NO GB
PW PH
PA NI
PL SE
QA AE
RO RU
RU SE
AG KN
LC VC
WS TO
SC TZ
SB VU
SE DE
TH VN
TT VE
GB DE
RE MU
RE SC
RE MG
YT KM
MQ DM
MQ LC
MQ BB
GP AG
GP DM
GP MS
MF AI
MF BL
BL AG
BL AI
BL KN
BL SX
PF KI
WF FJ
WF WS
WF TO
WF TV
PM CA
FK AR
KY HN
KY JM
TC BS
AI AG
AI VG
AI SX
AI VI
MS AG
MS KN
VG PR
VG VI
IO MV
AW CW
AW VE
CW VE
PR DO
PR VI
VI SX
GU MP
AS WS
AS TO
AX SE
AX NO
AX FI
CK KI
CK AS
CK PF
CK NU
CK TK
FO IS
FO NO
FO GB
GG FR
IM GB
GG GB
GG JE
JE FR
NF NZ
NF NC
NU TO
NU AS
PN PF
SJ NO
SJ RU
SJ IS
TK KI
TK WS
TK AS
TK WF
UM KI
UM HT
UM JM
UM MH
TF KM
TF MG
TF MU
TF SC
TF HM
TF MZ
BQ VE
BQ AW
BQ CW
BQ KN
BQ SX
BQ BL
JP CN
JP KP
JP KR
JP PH
NZ FJ
NZ TO
NZ WS
NZ KI
IS GL
RU US
ID PG
ID AU
END_MPAIRS

for my $line (@land_pairs, @maritime_same_plate_pairs) {
    $line =~ s/^\s+|\s+$//g;
    next unless length $line;
    my ($a, $b) = split ' ', $line;
    $neighbor{$a}{$b} = 1;
    $neighbor{$b}{$a} = 1;
}

1;

# --- Example usage ---------------------------------------------------
# use lib '.';      # or wherever GeologicalNeighbors.pm lives
# use GeologicalNeighbors qw(%neighbor);
# if ($neighbor{FR}{DE}) { print "France and Germany share a border\n"; }
#
# for my $n (sort keys %{ $neighbor{BR} }) {
#     print "Brazil borders $n\n";
# }
#
