#
# Configuration for the Paleobiology Database data service application
#

data_provider: "The Paleobiology Database"
data_source: "The Paleobiology Database"
data_license:  "Creative Commons CC-BY"
license_url:   "http://creativecommons.org/licenses/by/4.0/"
contact_email:   "admin@paleobiodb.org"
contact_name:    "the database administrator"

charset: "utf-8"
show_errors: 0
log: "error"
log_file: "pbapi_error_log"
request_log: 1

port: 3000
workers: 5
ds_debug: 0

test_port: 3999
test_db: pbdbTEST

stream_threshold: 102400

1.1:
    default_limit: 500

bins:
  - { resolution: 6.0 }
  - { resolution: 2.0 }
  - { resolution: 0.5 }

checks:
    max_synonym_no: 212734
    max_synonym_limit: 65

alert_file: "../pbdb-main/alert.txt"

gplates_uri: "https://macrostrat.org/gplates/reconstruct"
gplates_max_age: 550
gplates_feature_limit: 50

template_toolkit:
    COMPILE_EXT: ".ttc"

plugins:
    Database:
      driver: 'mysql'
      database: 'pbdb'
      host: 'mariadb'
      port: 3306
      username: 'pbdbuser'
      password: 'pbdbpwd'
      dbi_params:
        RaiseError: 1
        AutoCommit: 1
